import { ColorModeScript } from '@chakra-ui/react';
import theme from '@themes/default.theme';
import { Providers } from './providers';
import './globals.scss';

export const metadata = {
  title: 'Porfolio',
  description: 'Generated by create next app',
};

const RootLayout = async ({ children }) => {
  return (
    // TODO: Adding suppressHydrationWarning eliminates the console problem. it's apparently a known issue https://github.com/chakra-ui/chakra-ui/issues/7040
    <html lang="en" suppressHydrationWarning={true}>
      <body suppressHydrationWarning={true}>
        <ColorModeScript initialColorMode={theme.config.initialColorMode} />
        <Providers
        >
          {children}
        </Providers>
      </body>
    </html>
  );
};

export default RootLayout;
